const MarketList = [
    {
    Ahmednagar: [
      "Ahmednagar",
      "Jamkhed",
      "Kopargaon",
      "Newasa",
      "Pathardi",
      "Rahata",
      "Rahuri",
      "Rahuri(Vambori)",
      "Sangamner",
      "Shevgaon",
      "Shevgaon(Bodhegaon)",
      "Shrigonda",
      "Shrirampur",
      "Shrirampur(Belapur)",
      "Om Chaitanya Multistate Agro Purpose CoOp Society ",
      "Shrigonda(Gogargaon)",
      "Rahuri(Songaon)",
      "Akole",
      "Newasa(Ghodegaon)",
      "Parner",
      "Karjat",
      "Shree Sairaj Krushi Market",
    ],
    Akola: [
      "Akola",
      "Akot",
      "Balapur",
      "Murtizapur",
      "Patur",
      "Telhara",
      "Barshi Takli",
      "Late Vasantraoji Dandale Khajgi Krushi Bazar",
      "Shri Gajanan Maharaj Khajagi Krushi Utpanna Bazar",
    ],
    Amarawati: [
      "Amrawati(Frui & Veg. Market)",
      "Achalpur",
      "Amarawati",
      "Chandur Bazar",
      "Shetkari Khushi Bazar",
      "Anajngaon",
      "Daryapur",
      "Dharni",
      "Morshi",
      "Nanggaon",
      "Dhamngaon-Railway",
      "Varud",
      "Varud(Rajura Bazar)",
      "Chandur Railway",
    ],
    Aurangabad: [
      "Aurangabad",
      "Gangapur",
      "Kannad",
      "Lasur Station",
      "Paithan",
      "Sillod",
      "Sillod(Bharadi)",
      "Vaijpur",
      "Fulmbri",
      "Khultabad",
      "Bhagyoday Cotton and Agri Market ",
    ],
    Beed: [
      "Beed",
      "Gevrai",
      "Kada",
      "Kaij",
      "Kille Dharur",
      "Majalgaon",
      "Parali Vaijyanath",
      "Vadvani",
      "Ambejaogai",
      "Kai Madhavrao Pawar Khajgi Krushi Utappan Bazar Sa",
      "Kada(Ashti)",
    ],
    Bhandara: ["Bhandara", "Lakhandur", "Pavani", "Tumsar"],
    Buldhana: [
      "Chikali",
      "Deoulgaon Raja",
      "Khamgaon",
      "Lonar",
      "Nandura",
      "Shegaon",
      "Malkapur",
      "BSK Krishi Bazar Private Ltd",
      "Buldhana(Dhad)",
      "Jalgaon Jamod(Aasalgaon)",
      "Jaykissan Krushi Uttpan Khajgi Bazar ",
      "Mehekar",
      "Sangrampur(Varvatbakal)",
      "Sindkhed Raja",
      "ACF Agro Marketing ",
      "Deulgaon Raja Balaji Agro Marketing Private Market",
      "Maharaja Agresen Private Krushi Utappan Bazar Sama",
      "Buldhana",
    ],
    Chandrapur: [
      "Chandrapur",
      "Chandrapur(Ganjwad)",
      "Rajura",
      "Varora",
      "Bhadrawati",
      "Chimur",
      "Gondpimpri",
      "Korpana",
      "Pombhurni",
    ],
    Dhule: [
      "Dhule",
      "Dondaicha",
      "Dondaicha(Sindhkheda)",
      "Sakri",
      "Shirpur",
      "Janata Agri Market (DLS Agro Infrastructure Pvt Lt",
      "Pratap Nana Mahale Khajgi Bajar Samiti ",
    ],
    Gadchiroli: ["Aheri", "Sironcha", "Armori(Desaiganj)"],
    Hingoli: [
      "Akhadabalapur",
      "Hingoli",
      "Hingoli(Kanegoan Naka)",
      "Jawala-Bajar",
      "Sengoan",
      "Vitthal Krushi Utpanna Bazar ",
      "Basmat",
      "Marathawada Shetkari Khajgi Bazar Parisar",
      "Basmat(Kurunda)",
      "Kalamnuri",
      "Gajanan Krushi Utpanna Bazar (India) Pvt Ltd ",
      "Sant Namdev Krushi Bazar, ",
    ],
    Jalana: [
      "Ambad (Vadigodri)",
      "Ashti(Jalna)",
      "Bhokardan",
      "Bhokardan(Pimpalgaon Renu)",
      "Jalana",
      "Mantha",
      "Partur",
      "Ghansawangi",
      "Jafrabad",
      "Jalna(Badnapur)",
      "Partur(Vatur)",
    ],
    Jalgaon: [
      "Jalgaon",
      "Amalner",
      "Chalisgaon",
      "Chopada",
      "Dharangaon",
      "Jalgaon(Masawat)",
      "Pachora",
      "Parola",
      "Raver",
      "Yawal",
      "Bhusaval",
      "Gopal Krishna Agro",
      "J S K Agro Market ",
      "Jamner",
      "Mahavir Agri Market",
      "Shantilal Jain Agro",
      "Jamner(Neri)",
      "Pachora(Bhadgaon)",
      "Raver(Sauda)",
      "Yashika Agro Marketing",
    ],
    Kolhapur: ["Kolhapur", "Vadgaonpeth", "Kolhapur(Malkapur)", "Gadhinglaj"],
    Latur: [
      "Chakur",
      "Ahmedpur",
      "Aurad Shahajani",
      "Ausa",
      "Devani",
      "Jalkot",
      "Latur",
      "Latur(Murud)",
      "Nilanga",
      "Udgir",
    ],
    Mumbai: ["Fruit Market", "Mumbai", "Vashi New Mumbai"],
    Nagpur: [
      "Nagpur",
      "Bhiwapur",
      "Mandhal",
      "MS Kalpana Agri Commodities Marketing",
      "Ramtek",
      "Umared",
      "Hingna",
      "Kalmeshwar",
      "Kamthi",
      "Parshiwani",
      "Katol",
      "Mauda",
      "Narkhed",
      "Savner",
    ],
    Nanded: [
      "Bhokar",
      "Biloli",
      "Deglur",
      "Dharmabad",
      "Loha",
      "Mukhed",
      "Naigaon",
      "Nanded",
      "Hadgaon(Tamsa)",
      "Himalyatnagar",
      "Kandhar",
      "Kinwat",
      "Shetkari Khajgi Bajar",
      "Mudkhed",
      "Umari",
      "Hadgaon",
    ],
    Nandurbar: [
      "Nandurbar",
      "Shahada",
      "Taloda",
      "Akkalkuwa",
      "Navapur",
      "Dhadgaon",
    ],
    Nashik: [
      "Nasik",
      "Devala",
      "Kalvan",
      "Lasalgaon",
      "Lasalgaon(Niphad)",
      "Malegaon",
      "Manmad",
      "Nampur",
      "Nandgaon",
      "Satana",
      "Sinner",
      "Yeola",
      "Lasalgaon(Vinchur)",
      "Mankamneshwar Farmar Producer CoLtd Sanchalit Mank",
      "Chandvad",
      "Ghoti",
      "Dindori",
      "Dindori(Vani)",
      "Pimpalgaon",
      "Pimpalgaon Baswant(Saykheda)",
      "Umrane",
      "Malharshree Farmers Producer Co Ltd",
      "Shivsiddha Govind Producer Company Limited Sanchal",
      "Shree Rameshwar Krushi Market ",
      "Suragana",
    ],
    Osmanabad: [
      "Kalamb(Osmanabad)",
      "Paranda",
      "Tuljapur",
      "Murim",
      "Umarga",
      "Osmanabad",
      "Washi(Osmanabad)",
    ],
    Parbhani: [
      "Pathari",
      "Selu",
      "Sonpeth",
      "Manwat",
      "Jintur",
      "Palam",
      "Parbhani",
      "Shree Salasar Krushi Bazar ",
      "Tadkalas",
      "Purna",
      "Gangakhed",
      "Bori",
    ],
    Pune: [
      "Pune",
      "Pune(Moshi)",
      "Baramati",
      "Dound",
      "Indapur",
      "Indapur(Bhigwan)",
      "Nira(Saswad)",
      "Shirur",
      "Indapur(Nimgaon Ketki)",
      "Junnar",
      "Junnar(Narayangaon)",
      "Junnar(Otur)",
      "Khed",
      "Khed(Chakan)",
      "Maanachar",
      "Pune(Khadiki)",
      "Pune(Manjri)",
      "Pune(Pimpri)",
      "Mulshi",
      "Nira",
      "Junnar(Alephata)",
    ],
    Raigad: ["Karjat(Raigad)", "Panvel", "Pen", "Alibagh", "Mangaon", "Murud"],
    Ratnagiri: ["Ratnagiri (Nachane)"],
    Sangli: [
      "Sangli(Phale, Bhajipura Market)",
      "Sangli",
      "Palus",
      "Islampur",
      "Vita",
      "Tasgaon",
    ],
    Satara: ["Palthan", "Vaduj", "Karad", "Patan", "Satara", "Vai", "Lonand"],
    Sholapur: [
      "Solapur",
      "Akluj",
      "Barshi",
      "Dudhani",
      "Karmala",
      "Mangal Wedha",
      "Pandharpur",
      "Akkalkot",
      "Barshi(Vairag)",
      "Kurdwadi",
      "Kurdwadi(Modnimb)",
      "Mohol",
      "Laxmi Sopan Agriculture Produce Marketing Co Ltd",
    ],
    Thane: [
      "Kalyan",
      "Ulhasnagar",
      "Murbad",
      "Shahapur",
      "Bhivandi",
      "Palghar",
      "Vasai",
    ],
    Vashim: [
      "Manora",
      "Karanja",
      "Jai Gajanan Krishi Bazar",
      "Krushna Krishi Bazar ",
      "Malegaon(Vashim)",
      "Mangrulpeer",
      "N N Mundhada Agriculture Market Produce ",
      "Risod",
      "Washim",
      "Washim(Ansing)",
    ],
    Wardha: [
      "Hinganghat",
      "Wardha",
      "Arvi",
      "Ashti",
      "Ashti(Karanja)",
      "Pulgaon",
      "Samudrapur",
      "Sindi",
      "Sindi(Selu)",
    ],
    Yavatmal: [
      "Digras",
      "Mahesh Krushi Utpanna Bazar, Digras",
      "Pusad",
      "Cottoncity Agro Foods Private Ltd",
      "Kisan Market Yard",
      "Pandhakawada",
      "Ramdev Krushi Bazaar",
      "Shekari Krushi Khajgi Bazar",
      "Vani",
      "Yeotmal",
      "ZariZamini",
      "Babhulgaon",
      "Darwha",
      "Ghatanji",
      "Jagdamba Agrocare",
      "Mahagaon",
      "Mahavira Agricare",
      "Maregoan",
      "Ner Parasopant",
      "Ralegaon",
      "Aarni",
      "Umarked(Danki)",
      "Umarkhed",
      "Kalamb",
      "Bori Arab",
    ],
  },
];

export default MarketList;
